### ISSUE TITLE
Error from HDF5 file

### ISSUE THREAD

**Issue by abarciauskas-bgse** [developmentseed/raster-uploader#50]
I'm getting an error from trying to process an HDF5 file. I made 2 attempts once the polling step was fixed:

1. Upload 147 - No supported rasters found!

![screencapture-raster-uploader-upload-147-2022-08-11-15_57_46](https://user-images.githubusercontent.com/15016780/184259593-17299e89-7325-4871-922e-55fcb7f3a0f1.png)

2. Upload 148 - No processing pipeline
![screencapture-raster-uploader-upload-148-2022-08-11-16_34_04](https://user-images.githubusercontent.com/15016780/184259600-544cfde7-b70b-4e64-97d3-ab60b917dc67.png)

All the datasets it looks like have been used in testing are NetCDF so I'm _assuming_ HDF5 format are driving these errors but I can't say for sure. I also tried a netcdf file and that detects the variables but then I'm not able to select a variable by clicking around

![screencapture-raster-uploader-upload-149-2022-08-11-16_39_04](https://user-images.githubusercontent.com/15016780/184259940-7467b745-5c99-4b38-8f8e-994e7e911ecc.png)

**Comment by ingalls** [comment]
Closed via: https://github.com/developmentseed/raster-uploader/pull/55

Let's open targeting issues for specific problems with find with the new HDF5 processing pipeline
